[tools]
awscli = "latest"
bat = "latest"
btop = "latest"
chezmoi = "latest"
dust = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
kubectl = "latest"
kubeseal = "latest"
node = "lts"
python = "3.13"
ripgrep = "latest"
starship = "latest"
usage = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
